# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72b4bade0f56e92d01a8820b3c0080685686965b9b55830a1bd981bcd09aad8bf3bbe5308845242b4ac198ae2bc32bbc76ada4aa69957e6d63f8f89caaf8994b

test:
  secret_key_base: b0b8ae1284692bf0666d7d4125210334102bcf1f511441f80c6d0248d146053040c7e321fe0601cad1adbadbf95315fdd7c815ebe1ab792b1d091d1bffe0c8b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
